[package]
name = "lowpass_filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.5.1"
plotters = "0.3.6"
rand = "0.8.5"
